make:
	cabal build

test0:
	./start.sh ./settings/s0.txt
	python visualisation.py

test1:
	./start.sh ./settings/s1.txt
	python visualisation.py

test2:
	./start.sh ./settings/s2.txt
	python visualisation.py

test3:
	./start.sh ./settings/s3.txt
	python visualisation.py

test4:
	./start.sh ./settings/s4.txt
	python visualisation.py

test5:
	./start.sh ./settings/s5.txt
	python visualisation.py

test6:
	./start.sh ./settings/s6.txt
	python visualisation.py